applications:
    app:
        type: 'nodejs:20'
        web:
            commands:
                start: 'node server.js'

routes:
    "https://{default}/":
        type: upstream
        upstream: "app:http"
    "http://{default}/":
        type: redirect
        to: "https://{default}/"
